-- AlterTable
ALTER TABLE "Portfolio" ADD COLUMN     "lastBuyAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "averageBuyPrice" SET DATA TYPE DECIMAL(15,2);

-- AlterTable
ALTER TABLE "Stock" ALTER COLUMN "currentPrice" SET DATA TYPE DECIMAL(15,2);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(15,2);
